### ISSUE TITLE
Decompressing everytime

### ISSUE THREAD

**Issue by tzukav** [clyfish/ngx_unbrotli#1]
Hi, 
It seems like this module decompresses the response everytime regardless of the accept-encoding header.
I thought that the problem was here: 
![image](https://github.com/clyfish/ngx_unbrotli/assets/79611386/f98f2394-6e63-4dea-acec-e8f46ad111e5)
I tried to modify this part, but nothing works.
I'm using nginx 1.25.
Does the API changed or something?
Thanks.

**Comment by clyfish** [comment]
Hi, @tzukav 
Is there any `Accept-Encoding` request header contains `br`?
```bash
curl -H"Accept-Encoding: br" {URL}
```
You can check the return value of `ngx_http_unbrotli_check_request`.
If `ngx_http_unbrotli_check_request` returns `NGX_OK`, this filter module will not decompress the brotli compressed response.

**Comment by tzukav** [comment]
Of course it is, seems like this function `check_accept_encoding` does not detect the "br" value from "accept-encoding"

**Comment by tzukav** [comment]
Also, if you are debugging this module with cloudflare enabled, consider adding `Cache-Control: no-transform`, to disable brotli from cloudflare's side.
I'm not a c developer, so I don't really know how to debug/test/modify this module. I tried my best with it, but no success :(

**Comment by clyfish** [comment]
My nginx version is openresty/1.21.4.1.
Can you check the module with openresty/1.21.4.1?
I'll check it with nginx 1.25 this weekend.

**Comment by tzukav** [comment]
I tested with openresty 1.21.4.1rc3 and nginx 1.20, both same results. decompressing everytime.
I get to think is something wrong with the way I'm doing it?
Basically I'm trying to compress the response from a server block to another, you know, to store proxy_pass cache brotled and serving it directly to the user, and decompressing it only if the user does not support brotli.
Basically this is the way I'm trying to do it: 
![image](https://github.com/clyfish/ngx_unbrotli/assets/79611386/bb1d0462-06cf-4c4f-b615-611a3e33a2d6)
This method actually works with gzip and gunzip.

*ignore the fact that there's 2 brotli on directives, i just put that in there for example purposes

**Comment by clyfish** [comment]
nginx.conf without `unbrotli`:
```nginx
server {
    listen  8080;
    location = /jquery.min.js {
        #unbrotli on;
        proxy_set_header Accept-Encoding br;
        proxy_pass https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js;
    }
}
```
Test result without `unbrotli`:
```bash
$ curl -s 127.0.0.1:8080/jquery.min.js | wc -c
27958
$ curl -sH"Accept-Encoding: br" 127.0.0.1:8080/jquery.min.js | wc -c
27958
```

nginx.conf with `unbrotli`:
```nginx
server {
    listen  8080;
    location = /jquery.min.js {
        unbrotli on;
        proxy_set_header Accept-Encoding br;
        proxy_pass https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js;
    }
}
```
Test result with `unbrotli`:
```bash
$ curl -s 127.0.0.1:8080/jquery.min.js | wc -c
89476
$ curl -sH"Accept-Encoding: br" 127.0.0.1:8080/jquery.min.js | wc -c
27958
```

**Comment by tzukav** [comment]
interesting, your code doesn't work either, now I'm thinking that there's a problem when I compile it.
So, your instructions didn't work for me 100%,  I get to change cmake3 to cmake, I don't think that's a problem now. But those brotli paths from the config file don't work for me, mine goes to ~/local/brotli/lib, but the name and the extension is changed. The extension is .so, I think they are compiled or something.
This is my brotli/lib folder:
![image](https://github.com/clyfish/ngx_unbrotli/assets/79611386/c63ba0c2-e775-466b-aef1-4f3a8ea2bbd4)
As you can see, I get no .a files.
It may be a platform problem? I'm on ubuntu 22.04.
How to get those .a files?
Thank you.

**Comment by clyfish** [comment]
Is your OS/compiler 32-bit or 64-bit?
You can check with these commands:
```bash
$ getconf LONG_BIT
64
$ cd ~/local/brotli/lib
$ file libbrotlicommon.so.1.0.9
libbrotlicommon.so.1.0.9: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=XXXX, not stripped
```

**Comment by tzukav** [comment]
yeah, it is 64 bits, and the file command result looks the same as yours.

**Comment by tzukav** [comment]
wanna test it out? I can give you a vps, I just need a way to contact you privately

**Comment by clyfish** [comment]
I've tested it on a fresh Ubuntu 22.04 docker image, and it works.

You can test it with this Dockerfile:
https://github.com/clyfish/ngx_unbrotli/blob/main/Dockerfile

Can you provide a Dockerfile instead of a vps to reproduce your problem?

**Comment by clyfish** [comment]
BTW, I updated [README.md](https://github.com/clyfish/ngx_unbrotli/blob/main/README.md), [build_brotli.sh](https://github.com/clyfish/ngx_unbrotli/blob/main/build_brotli.sh) and [config](https://github.com/clyfish/ngx_unbrotli/blob/main/config).

**Comment by clyfish** [comment]
Use these commands to build and run the Dockerfile:
```bash
docker build -t ngx_unbrotli:dev .
docker run -it ngx_unbrotli:dev
cd /usr/local/nginx
vi conf/nginx.conf # add ngx_unbrotli module to nginx config
./sbin/nginx
```

**Comment by tzukav** [comment]
I'm so sorry, everything is okay, It is just not working on domains that use cloudflare as a proxy.
Seems like cloudflare accept only gzip and not compressed from the origin, it just send "Accept-Encoding: gzip" regardless user's accept-encoding.
https://developers.cloudflare.com/support/speed/optimization-file-size/what-will-cloudflare-compress/#does-cloudflare-compress-resources
That's why your module does decompression everytime. I was right, it does not see "accept-encoding: br". because it just does not exist. :)

I tested the module directly on an IP now, everything seems to work...
Thank you for your time and your help.
