### ISSUE TITLE
An option to force uncompress always

### ISSUE THREAD

**Issue by dvershinin** [clyfish/ngx_unbrotli#2]
Is it possible to add something akin to `unbrotli_force` directive? In order to unconditionally decompress upstream's response, regardless of client's support. Similar to [gunzip_force here](https://github.com/Jas0n99/ngx_force_gunzip).

**Comment by clyfish** [comment]
[`ngx_force_gunzip`](https://github.com/Jas0n99/ngx_force_gunzip) is very simple.

You can fork [`ngx_unbrotli`](https://github.com/clyfish/ngx_unbrotli) and do it yourself.
